# Generated by Django 4.2 on 2024-11-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_achievement_facility_leadershipstaff_schoolhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Management', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='management_images/')),
                ('catalog_pdf', models.FileField(blank=True, null=True, upload_to='catalogs/')),
                ('catalog_doc', models.FileField(blank=True, null=True, upload_to='catalogs/')),
                ('phone', models.CharField(default='+1 5589 55488 55', max_length=15)),
                ('email', models.EmailField(default='contact@example.com', max_length=254)),
            ],
        ),
    ]
