# Generated by Django 4.2 on 2024-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feature_service_studentleadershipsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the leadership section', max_length=255)),
                ('description_1', models.TextField(help_text='First description for the leadership section')),
                ('description_2', models.TextField(help_text='Second description for the leadership section')),
                ('read_more_link', models.URLField(blank=True, help_text="Optional link for the 'Read More' button", null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentLeadershipSection',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='points',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(help_text='Main description for the feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='heading',
            field=models.CharField(help_text='Heading for the feature content', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon_class',
            field=models.CharField(help_text='CSS class for the tab icon', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the feature', null=True, upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='italic_description',
            field=models.TextField(blank=True, help_text='Italicized description for the feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='tab_id',
            field=models.SlugField(help_text='Unique ID for the tab (used in HTML)', unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='tab_title',
            field=models.CharField(help_text='Title of the tab', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='details_url',
            field=models.URLField(help_text='URL for more details about the service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(help_text='CSS class for the service icon', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_color',
            field=models.CharField(default='#000000', help_text='Color for the service icon (hex code)', max_length=7),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Title of the service', max_length=255),
        ),
    ]
